### ISSUE TITLE
issue while installing Sumsub in android & IOS

### ISSUE THREAD

**Issue by selfishprogrammer** [SumSubstance/react-native-mobilesdk-module#10]
When i am Trying to Link Sumsub in my react native project i am getting following issue 
<img width="882" alt="Screenshot 2023-12-25 at 3 19 39 AM" src="https://github.com/SumSubstance/react-native-mobilesdk-module/assets/58311914/b0f6bc25-42c5-4d37-8fab-44eed0e7a70d">

and following in Android 
<img width="893" alt="Screenshot 2023-12-25 at 3 21 43 AM" src="https://github.com/SumSubstance/react-native-mobilesdk-module/assets/58311914/13318aab-0ac7-4312-ad7b-b450df1f4f0a">

I followed Docs instructions but getting same issue , need your inputs in this thanks 

RN version : -> 0.72.4
Deployment target IOS : 14.1 
sumsub version: 1.28.0

**Comment by money-development** [comment]
@selfishprogrammer Did you manage to solve the problem on Android? I have the same

**Comment by selfishprogrammer** [comment]
@dzengi  yeah i solved it by adding 
```
allprojects {
  repositories {
      maven { url "https://maven.sumsub.com/repository/maven-public/" }
      mavenCentral()
  }
}
```

outside buildscript;



```
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24
        compileSdkVersion = 34
        targetSdkVersion = 34
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }

    repositories {
        // maven { url "https://maven.sumsub.com/repository/maven-public/" }  
    google() 
     mavenCentral()
      
    }

    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath 'com.google.gms:google-services:4.3.15'
    }
    

}

allprojects {
  repositories {
      maven { url "https://maven.sumsub.com/repository/maven-public/" }
      mavenCentral()
  }
}
```

Hope it will fix your issue thanks 😊
