### ISSUE TITLE
Sumsub uploads users' installed applications informations on Android

### ISSUE THREAD

**Issue by felipecamposfabel** [SumSubstance/react-native-mobilesdk-module#17]
Recently my app got rejected on Google Play for the following reason:

> Your app is uploading users' Installed applications information to https://api.sumsub.com/ without a prominent disclosure.

I'm already initializing the SDK using `.withAnalyticsEnabled(false)`. With that, Google requires an in-app Prominent Disclosure. Meaning no T&C/Privacy Policy, and no menus. It needs to be disclosed under the app's normal usage.

So, if that's true, could you explain why you need this information so I can communicate it to my users correctly?

**Comment by nam-hoai-tran** [comment]
Hi, I'm also having the same problem submitting our Android app. Please help us on how to solve this issue.

**Comment by felipecamposfabel** [comment]
@nam-hoai-tran  I reached out to their support. I upgraded the SDK to 1.33.1, resubmitted the app and the issue was solved.

**Comment by nam-hoai-tran** [comment]
@felipecamposfabel thank you very much for the info
